backbase-statics:
  job:
    imports:
      - repository: https://repo.backbase.com
        ## API KEY to access JFrog Artifactory repository
        ## For other repositories use own keys
        apikey:
        ## Username and password in case you don't want to use an API KEY to access JFrog Artifactory
        ## IMPORTANT! only 1 authentication method is required
        username: <yourRepoUsername>
        password: <yourRepoPassword>
        statics:
          - /backbase-6-release/com/backbase/tools/cx/cx6-import-tool-cli/6.2.9-b1/cx6-import-tool-cli-6.2.9-b1.jar
          - /backbase-6-release/com/backbase/cxp/editorial-collection/b3683/editorial-collection-b3683.zip
          - /expert-release-local/com/backbase/web-sdk/collection/collection-bb-web-sdk/1.13.1/collection-bb-web-sdk-1.13.1.zip
          - /backbase-6-release/com/backbase/cxp/experience-manager/b3683/experience-manager-b3683.zip
