apiVersion: v2
name: local-k8s
description: A Helm Chart for Backbase Customer Experience Services
version: 0.4.0
appVersion: 6.2.10
keywords:
  - backbase
  - cxs
maintainers:
  - name: Andrés Torres
    email: andres@backbase.com
  - name: Dhananjay Singh
    email: dhananjay@backbase.com
icon: https://start.backbase.com/favicon.png

dependencies:
  - name: backbase-env
    repository: https://repo.backbase.com/backbase-charts
    version: 0.5.48
  - name: ips-edge
    repository: https://repo.backbase.com/backbase-charts
    version: 0.10.1
#  - name: cxs
#    repository: https://repo.backbase.com/backbase-charts
#    version: 0.8.0
#  - name: backbase-statics
#    repository: https://repo.backbase.com/backbase-charts
#    version: 0.1.8
#  - name: nginx-ingress
#    repository: https://helm.nginx.com/stable
#    version: 0.7.1
  - name: identity
    repository: https://repo.backbase.com/backbase-charts
    version: 0.12.0

