global:
  env:
    "EUREKA_CLIENT_ENABLED": "false"
    "SPRING_CLOUD_KUBERNETES_ENABLED": "true"
    "SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED": "true"
    "SPRING_CLOUD_KUBERNETES_RIBBON_MODE": "SERVICE"
    "spring.cloud.loadbalancer.ribbon.enabled": "false"
    "spring.autoconfigure.exclude": "org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration"
    # Enabling RBAC roles creation as it's disabled by default
  rbac:
    create: true
  app:
    image:
      registry: repo.backbase.com/backbase-docker-releases
  chartName: local-k8s
  database:
    host: mysql
    existingSecret: mysql
    urlTemplate: "jdbc:mysql://{{.database.host}}:{{.database.port}}/{{.database.sid}}?useSSL=false"
  activemq:
    host: activemq
    existingSecret: activemq
  jwt:
    existingSecret: local-k8s-jwt
  registry:
    enabled: false

backbase-env:
  fullnameOverride: local-k8s
  activemq:
    enabled: true
    fullnameOverride: activemq
  mysql:
    enabled: true
    mysqlRootPassword: backbase321!
    mysqlPassword: backbase123
    fullnameOverride: mysql
  jwt:
    enabled: true
    internalSecretKey: "JWTSecretKeyDontUseInProduction!"
    externalSecretKey: "JWTSecretKeyDontUseInProduction!"
    externalEncSecretKey: "JWTEncKeyDontUseInProduction666!"
    userctxKey: "JWTSecretKeyDontUseInProduction!"

ips-edge:
  edge:
    env:
      GATEWAY_ACTUATOR_USER: "admin"
      GATEWAY_ACTUATOR_PASSWORD: "admin"
    app:
      name: edge
      image:
        repository: edge
        tag: IPS-1.12.0
    service:
      enabled: true
      nameOverride: edge
    ingress:
      enabled: true
      annotations:
        "kubernetes.io/ingress.class": "nginx"
        "nginx.ingress.kubernetes.io/proxy-body-size": "50m"
        "nginx.ingress.kubernetes.io/ssl-redirect": "false"
      hosts:
        - host: "kubernetes.docker.internal"
          paths:
            - /

ips-authentication-dev:
  authentication-dev:
    app:
      image:
        repository: authentication-dev
        tag: IPS-1.12.0-no-production
    service:
      enabled: true
      nameOverride: auth

ips-bas-token-converter:
  bas-token-converter:
    env:
      "SPRING_AUTOCONFIGURE_EXCLUDE": "org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration"
    app:
      image:
        repository: bb-authentication-token-converter-service
        tag: IPS-1.12.0
    service:
      enabled: true
      nameOverride: token-converter

cxs:
  auditing:
    enabled: false
    app:
      name: auditing
      image:
        repository: auditing
    database:
      sid: cx6_audit
    service:
      enabled: true
      nameOverride: auditing

  contentservices:
    enabled: true
    app:
      name: contentservices
      image:
        repository: contentservices
        tag: CXS-6.2.5
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_contentservices
    service:
      enabled: true
      nameOverride: contentservices

  portal:
    enabled: true
    app:
      name: portal
      image:
        # Provide here correct Docker image (portal-exec-jar)
        repository: portal
        tag: CXS-6.2.5
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_portal
    service:
      enabled: true
      nameOverride: portal
    env:
      PORTAL_RESOURCELOCATION_PROFILE: "filesystem"
      PORTAL_RESOURCELOCATION_PATH: "/tmp"
      # For Portal hibernate dialect is a required property for starting up:
      #
      # - mysql = org.hibernate.dialect.MySQL5Dialect
      # - sqlserver = org.hibernate.dialect.SQLServer2012Dialect
      # - oracle = org.hibernate.dialect.Oracle12cDialect
      #
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL5Dialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_SESSIONFACTORYNAMEISJNDI: "false"
      #  Currently Portal image uses '/portal', will be aligned with other images
  #            SERVER_SERVLET_CONTEXT_PATH: "/"
  provisioning:
    enabled: true
    app:
      name: provisioning
      image:
        repository: provisioning
        tag: CXS-6.2.5
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_provisioning
    service:
      enabled: true
      nameOverride: provisioning

  pushintegrationservice:
    enabled: false
    app:
      name: pushintegrationservice
      image:
        repository: push-integration-service
        tag: CXS-6.2.5
    database:
      sid: cx6_push_integration
    env:
      "eureka.instance.non-secure-port": "8080"
    service:
      enabled: true
      nameOverride: pushintegrationservice
  renditionservice:
    enabled: false
    app:
      name: renditionservice
      image:
        repository: renditionservice
        tag: CXS-6.2.5
    database:
      sid: cx6_renditionservice
    env:
      "renditionservice.extension-points.enabled": "true"
    service:
      enabled: true
      nameOverride: renditionservice
  targeting:
    enabled: false
    app:
      name: targeting
      image:
        repository: targeting
        tag: CXS-6.2.5
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_targeting
    service:
      enabled: true
      nameOverride: targeting
  thumbnailservice:
    enabled: false
    app:
      name: thumbnailservice
      image:
        repository: thumbnailservice
        tag: CXS-6.2.5
    service:
      enabled: true
      nameOverride: thumbnailservice
  space-controller:
    enabled: false
    app:
      name: space-controller
      image:
        repository: space-controller
        tag: CXS-6.2.5
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_space_controller
    env:
      "SPRING_APPLICATION_NAME": "space-controller"
    service:
      enabled: true
      nameOverride: space-controller
  versionmanagementpersistenceservice:
    enabled: false
    app:
      name: versionmanagementpersistenceservice
      image:
        repository: versionmanagement-persistence-service
        tag: CXS-6.2.5
      resources:
        cpu:
          minShares: 100
          maxShares: 1000
    database:
      sid: cx6_versionmanagement
    service:
      enabled: true
      nameOverride: versionmanagementpersistenceservice

backbase-statics:
  image:
    registry: docker.io
    repository: torrespro/import-statics
    tag: latest
  job:
    imports:
      - repository: https://repo.backbase.com
        ## API KEY to access JFrog Artifactory repository
        ## For other repositories use own keys
        apikey:
        ## Username and password in case you don't want to use an API KEY to access JFrog Artifactory
        ## IMPORTANT! only 1 authentication method is required
        username: trainingbe2020wk22
        password: tQ<nBpD$bmDF
        statics:
          - /backbase-6-release/com/backbase/tools/cx/cx6-import-tool-cli/6.2.5-b64/cx6-import-tool-cli-6.2.5-b64.jar
          - /backbase-6-release/com/backbase/cxp/editorial-collection/b3591/editorial-collection-b3591.zip
          - /expert-release-local/com/backbase/web-sdk/collection/collection-bb-web-sdk/1.11.0/collection-bb-web-sdk-1.11.0.zip
          - /backbase-6-release/com/backbase/cxp/experience-manager/b3591/experience-manager-b3591.zip
    target:
      context: http://edge:8080/api/provisioning
      auth-url: http://edge:8080/api/auth/login
      identity-real:
      username: admin
      password: admin
      retry-max-attempts: 200
      retry-back-off-period: 2000

    check:
      enabled: true
      targets:
        - name: Authentication
          url: http://edge:8080/api/auth/actuator/health
        - name: 8080/api/provisioning
          url: http://edge:8080/api/provisioning/actuator/health
