global:
  env:
    "EUREKA_CLIENT_ENABLED": "false"
    "SPRING_CLOUD_KUBERNETES_ENABLED": "true"
    "SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED": "true"
    "SPRING_CLOUD_KUBERNETES_RIBBON_MODE": "SERVICE"
    "spring.cloud.loadbalancer.ribbon.enabled": "false"
    "spring.autoconfigure.exclude": "org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration"
    # Enabling RBAC roles creation as it's disabled by default
  rbac:
    create: true
  app:
    image:
      registry: repo.backbase.com/backbase-docker-releases
  chartName: local-k8s
  database:
    enabled: true
    host: mysql
    type: mysql
    checkEnabled: true
    existingSecret: mysql
    urlTemplate: "jdbc:mysql://{{.database.host}}:{{.database.port}}/{{.database.sid}}?useSSL=false"
  activemq:
    enabled: true
    host: activemq
    existingSecret: activemq
  jwt:
    enabled: true
    existingSecret: local-k8s-jwt
    SIG_SECRET_KEY_fromSecret: true
    EXTERNAL_SIG_SECRET_KEY_fromSecret: true
    EXTERNAL_ENC_SECRET_KEY_fromSecret: true
    USERCTX_KEY_fromSecret: true
  registry:
    enabled: false

backbase-env:
  fullnameOverride: local-k8s
  activemq:
    enabled: true
    fullnameOverride: activemq
  mysql:
    enabled: true
    mysqlRootPassword: backbase321!
    mysqlPassword: backbase123
    fullnameOverride: mysql
  jwt:
    enabled: true
    internalSecretKey: "JWTSecretKeyDontUseInProduction!"
    externalSecretKey: "JWTSecretKeyDontUseInProduction!"
    externalEncSecretKey: "JWTEncKeyDontUseInProduction666!"
    userctxKey: "JWTSecretKeyDontUseInProduction!"

ips-edge:
  edge:
    env:
      GATEWAY_ACTUATOR_USER: "admin"
      GATEWAY_ACTUATOR_PASSWORD: "admin"
    app:
      image:
        repository: edge
        tag: IPS-1.12.6
    ingress:
      enabled: true
      annotations:
        "kubernetes.io/ingress.class": "nginx"
        "nginx.ingress.kubernetes.io/proxy-body-size": "50m"
        "nginx.ingress.kubernetes.io/ssl-redirect": "false"
      hosts:
        - host: "kubernetes.docker.internal"
          paths:
            - /

identity:
  backbaseidentity:
    database:
      sid: "backbase_identity"
    env:
      "quarkus.datasource.jdbc.transaction-isolation-level": "2"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_USER: "admin"
      QUARKUS_HTTP_CORS_ORIGINS: "http://kubernetes.docker.internal"
      KEYCLOAK_BACKBASE_SESSION_LIMIT_DEFAULT_STRATEGY: 'FIFO'
      KEYCLOAK_BACKBASE_SESSION_LIMIT_REALMS_BACKBASE_NAME: 'backbase'
      KEYCLOAK_BACKBASE_SESSION_LIMIT_REALMS_BACKBASE_CLIENTS_SESSIONLIMIT_NAME: 'session-limit'
      KEYCLOAK_BACKBASE_SESSION_LIMIT_REALMS_BACKBASE_CLIENTS_SESSIONLIMIT_STRATEGY: 'FIFO'
      KEYCLOAK_BACKBASE_SESSION_LIMIT_REALMS_BACKBASE_CLIENTS_SESSIONLIMIT_LIMIT: '2'
      JAVA_TOOL_OPTIONS: "-Dkeycloak.migration.action=import -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumeMounts:
      - mountPath: /tmp/keycloak-export/
        name: config
    volumes:
      - name: config
        configMap:
          name: identity-configmap:
          items:
            - key: backbase-realm.json
              path: backbase-realm.json
            - key: keycloak-add-user.json
              path: keycloak-add-user.json
    app:
      name: backbaseidentity
      image:
        repository: backbase-identity
        tag: IDENTITY-1.7.3
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: http
        - name: infinispan
          port: 7800
          protocol: TCP
    service:
      enabled: true
      nameOverride: backbaseidentity
      additionalPorts:
        - name: infinispan
          port: 7800
          protocol: TCP
          targetPort: infinispan
    ingress:
      enabled: true
      annotations:
        "kubernetes.io/ingress.class": "nginx"
        "nginx.ingress.kubernetes.io/proxy-read-timeout": "600"
        "nginx.ingress.kubernetes.io/proxy-buffer-size": "16k"
        "nginx.ingress.kubernetes.io/ssl-redirect": "false"
        #"nginx.ingress.kubernetes.io/use-regex": "true"
      hosts:
        - host: "identity.docker.internal"
          paths:
            - /
  oidctokenconverter:
    enabled: true
    env:
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_INTERNALHOST: 'identity.docker.internal'
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_ISSUERHOST: kubernetes.docker.internal
      SSO_JWT_EXTERNAL_EXPIRATION: 3600
      SSO_JWT_EXTERNAL_NOT_VALID_AFTER: 30000
      SSO_JWT_EXTERNAL_RENEW: 36000
    app:
      name: oidctokenconverter
      image:
        repository: oidc-token-converter-service
        tag: IDENTITY-1.7.3
  identityintegrationservice:
    enabled: false
  fidoservice:
    enabled: false
  devicemanagementservice:
    enabled: false
  confirmation:
    enabled: false
  transactionsigningmock:
    enabled: false
  hardtokenoutboundintegrationmock:
    enabled: false
  communicationsoutboundintegrationmock:
    enabled: false

cxs:
  auditing:
    enabled: false
    app:
      name: auditing
      image:
        repository: auditing
    database:
      sid: cx6_audit

  contentservices:
    enabled: true
    app:
      name: contentservices
      image:
        repository: contentservices
        tag: CXS-6.2.10
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_contentservices

  portal:
    enabled: true
    app:
      name: portal
      image:
        repository: portal
        tag: CXS-6.2.10
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_portal
    service:
      enabled: true
      nameOverride: portal
    env:
      PORTAL_RESOURCELOCATION_PROFILE: "filesystem"
      PORTAL_RESOURCELOCATION_PATH: "/tmp"
      # For Portal hibernate dialect is a required property for starting up:
      #
      # - mysql = org.hibernate.dialect.MySQL5Dialect
      # - sqlserver = org.hibernate.dialect.SQLServer2012Dialect
      # - oracle = org.hibernate.dialect.Oracle12cDialect
      #
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL5Dialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_SESSIONFACTORYNAMEISJNDI: "false"
      #  Currently Portal image uses '/portal', will be aligned with other images
  #            SERVER_SERVLET_CONTEXT_PATH: "/"
  provisioning:
    enabled: true
    app:
      name: provisioning
      image:
        repository: provisioning
        tag: CXS-6.2.10
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_provisioning

  pushintegrationservice:
    enabled: false
    app:
      name: pushintegrationservice
      image:
        repository: push-integration-service
        tag: CXS-6.2.10
    database:
      sid: cx6_push_integration
    env:
      "eureka.instance.non-secure-port": "8080"
  renditionservice:
    enabled: false
    app:
      name: renditionservice
      image:
        repository: renditionservice
        tag: CXS-6.2.10
    database:
      sid: cx6_renditionservice
    env:
      "renditionservice.extension-points.enabled": "true"
  targeting:
    enabled: false
    app:
      name: targeting
      image:
        repository: targeting
        tag: CXS-6.2.10
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_targeting
  thumbnailservice:
    enabled: false
    app:
      name: thumbnailservice
      image:
        repository: thumbnailservice
        tag: CXS-6.2.10
  space-controller:
    enabled: false
    app:
      name: space-controller
      image:
        repository: space-controller
        tag: CXS-6.2.10
      resources:
        memory:
          ram: 1024
        cpu:
          minShares: 100
          maxShares: 2000
    database:
      sid: cx6_space_controller
    env:
      "SPRING_APPLICATION_NAME": "space-controller"
  versionmanagementpersistenceservice:
    enabled: false
    app:
      name: versionmanagementpersistenceservice
      image:
        repository: versionmanagement-persistence-service
        tag: CXS-6.2.10
      resources:
        cpu:
          minShares: 100
          maxShares: 1000
    database:
      sid: cx6_versionmanagement

backbase-statics:
  image:
    registry: docker.io
    repository: torrespro/import-statics
    tag: latest
  job:
    imports:
      - repository: https://repo.backbase.com
        ## API KEY to access JFrog Artifactory repository
        ## For other repositories use own keys
        apikey:
        ## Username and password in case you don't want to use an API KEY to access JFrog Artifactory
        ## IMPORTANT! only 1 authentication method is required
        username: <yourRepoUsername>
        password: <yourRepoPassword>
        statics:
          - /backbase-6-release/com/backbase/tools/cx/cx6-import-tool-cli/6.2.10-b1/cx6-import-tool-cli-6.2.10-b1.jar
          - /backbase-6-release/com/backbase/cxp/editorial-collection/2.0.0-b340/editorial-collection-2.0.0-b340.zip
          - /expert-release-local/com/backbase/web-sdk/collection/collection-bb-web-sdk/1.14.0/collection-bb-web-sdk-1.14.0.zip
          - /backbase-6-release/com/backbase/cxp/experience-manager/2.0.0-b340/experience-manager-2.0.0-b340.zip
    target:
      context: http://edge:8080/api/provisioning
      auth-url: http://backbaseidentity:8080
      identity-scope: openid
      identity-grant-type: password
      identity-client-id: bb-tooling-client
      identity-realm: backbase
      username: admin
      password: admin
      retry-max-attempts: 1500
      retry-back-off-period: 5000

    check:
      enabled: true
      targets:
        - name: Provisioning
          url: http://edge:8080/api/provisioning/actuator/health
        - name: Portal
          url: http://edge:8080/api/portal/actuator/health
        - name: Contentservices
          url: http://edge:8080/api/contentservices/actuator/health
        - name: Identity
          url: http://backbaseidentity:8080/auth/realms/backbase/.well-known/openid-configuration
