apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-configmap
data:
  backbase-realm.json: |-
{{ .Files.Get "support-files/backbase-realm.json" | indent 4}}
  keycloak-add-user.json: |-
{{ .Files.Get "support-files/keycloak-add-user.json" | indent 4}}